from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def generate_report(predicted_class, confidence):

    filename = "Structural_Defect_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>STRUCTURAL DEFECT DETECTION REPORT</b>", styles["Title"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph(f"<b>Prediction:</b> {predicted_class}", styles["Normal"]))

    story.append(Paragraph(f"<b>Confidence:</b> {confidence:.2%}", styles["Normal"]))

    # Severity
    if confidence >= 0.95:
        severity = "High"
    elif confidence >= 0.85:
        severity = "Medium"
    else:
        severity = "Low Confidence"

    story.append(Paragraph(f"<b>Severity:</b> {severity}", styles["Normal"]))

    # Recommendation
    if predicted_class == "crack":
        recommendation = "Immediate structural inspection is recommended."
    else:
        recommendation = "No visible structural defect detected."

    story.append(Paragraph(f"<b>Recommendation:</b> {recommendation}", styles["Normal"]))

    current_date = datetime.now().strftime("%d-%b-%Y %H:%M")

    story.append(Paragraph(f"<b>Date:</b> {current_date}", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("Generated by AI Structural Defect Detection System", styles["Italic"]))

    doc.build(story)

    return filename