from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def generate_report(predicted_class,confidence,severity,risk,recommendation,crack_percentage):

    filename = "Structural_Defect_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph(
            "<b>STRUCTURAL DEFECT DETECTION REPORT</b>",
            styles["Title"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            f"<b>Type of Defect:</b> {predicted_class}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence:.2%}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Severity:</b> {severity}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Risk Level:</b> {risk}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Estimated Crack Area:</b> {crack_percentage:.2f}%",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Recommendation:</b> {recommendation}",
            styles["Normal"]
        )
    )

    current_date = datetime.now().strftime("%d-%b-%Y %H:%M")

    story.append(
        Paragraph(
            f"<b>Date:</b> {current_date}",
            styles["Normal"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            "Generated by AI Structural Defect Detection System",
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename